geonode/contrib/services/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('geonode.contrib.services.views',
    url(r'^$', 'services', name='services'),
    url(r'^register/$', 'register_service', name="register_service"),
    (r'^registerbytype/$', 'register_service_by_type'),
    url(r'^(?P<service_id>\d+)/$', 'service_detail', name='service_detail'),
    url(r'^(?P<service_id>\d+)/edit$', 'edit_service', name='edit_service'),
    url(r'^(?P<service_id>\d+)/remove', 'remove_service', name='remove_service'),
    url(r'^(?P<service_id>\d+)/ajax-permissions$', 'ajax_service_permissions', name='ajax_service_permissions'),
)

geonode/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView

import geonode.proxy.urls

from geonode.api.urls import api

# Setup Django Admin
from django.contrib import admin
admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

urlpatterns = patterns('',

    # Static pages
    url(r'^/?$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
    url(r'^developer/$', TemplateView.as_view(template_name='developer.html'), name='developer'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),

    # Layer views
    (r'^layers/', include('geonode.layers.urls')),

    # Map views
    (r'^maps/', include('geonode.maps.urls')),

    # Catalogue views
    (r'^catalogue/', include('geonode.catalogue.urls')),

    # Search views
    url(r'^search/$', TemplateView.as_view(template_name='search/search.html'), name='search'),

    # Social views
    (r'^cas/', include('cas_consumer.urls')),
    (r"^account/", include("account.urls")),
    (r'^people/', include('geonode.people.urls')),
    (r'^avatar/', include('avatar.urls')),
    (r'^comments/', include('dialogos.urls')),
    (r'^ratings/', include('agon_ratings.urls')),
    (r'^activity/', include('actstream.urls')),
    (r'^announcements/', include('announcements.urls')),
    #(r'^notifications/', include('notification.urls')),
    (r'^messages/', include('user_messages.urls')),
    (r'^social/', include('geonode.social.urls')),
    # Accounts
    url(r'^account/ajax_login$', 'geonode.views.ajax_login',
                                       name='account_ajax_login'),
    url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup',
                                       name='account_ajax_lookup'),
    url(r'^security/permissions/(?P<type>[^/]*)/(?P<resource_id>\d+)$', 'geonode.security.views.resource_permissions',
                                       name='resource_permissions'),

    # Meta
    url(r'^lang\.js$', TemplateView.as_view(template_name='lang.js', content_type='text/javascript'), name='lang'),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog',
                                  js_info_dict, name='jscat'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
                                  {'sitemaps': sitemaps}, name='sitemap'),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^admin/', include(admin.site.urls)),
    url(r'', include(api.urls)),
    )

#Documents views
if 'geonode.documents' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^documents/', include('geonode.documents.urls')),
    )

if "geonode.contrib.groups" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^groups/', include('geonode.contrib.groups.urls')),
    )

if "geonode.contrib.services" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^services/', include('geonode.contrib.services.urls')),
    )

if "geonode.contrib.dynamic" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^dynamic/', include('geonode.contrib.dynamic.urls')),
    )

if 'geonode.geoserver' in settings.INSTALLED_APPS:
    # GeoServer Helper Views
    urlpatterns += patterns('', 
        # Upload views
        (r'^upload/', include('geonode.upload.urls')),
        (r'^gs/', include('geonode.geoserver.urls')),
    )

# Set up proxy
urlpatterns += geonode.proxy.urls.urlpatterns


# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

geonode/contrib/services/models.py
import logging
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from geoserver.catalog import FailedRequestError
from taggit.managers import TaggableManager
from geonode.security.models import PermissionLevelMixin
from geonode.security.enumerations import ANONYMOUS_USERS, AUTHENTICATED_USERS
from geonode.contrib.services.enumerations import SERVICE_TYPES, SERVICE_METHODS, GXP_PTYPES
from geonode.layers.models import Layer 
from geonode.people.models import Profile, Role
from django.utils.translation import ugettext_lazy as _
from django.db.models import signals

STATUS_VALUES = [
    'pending',
    'failed',
    'process'
]

logger = logging.getLogger("geonode.contrib.services")

"""
geonode.contrib.services
"""
class Service(models.Model, PermissionLevelMixin):
    """
    Service Class to represent remote Geo Web Services
    """

    type = models.CharField(max_length=4, choices=SERVICE_TYPES)
    method = models.CharField(max_length=1, choices=SERVICE_METHODS)
    base_url = models.URLField(unique=True,db_index=True) # with service, version and request etc stripped off
    version = models.CharField(max_length=10, null=True, blank=True)
    name = models.CharField(max_length=255, unique=True,db_index=True) #Should force to slug?
    title = models.CharField(max_length=255, null=True, blank=True)
    description = models.CharField(max_length=255, null=True, blank=True)
    abstract = models.TextField(null=True, blank=True)
    keywords = TaggableManager(_('keywords'), blank=True)
    online_resource = models.URLField(False, null=True, blank=True)
    fees = models.CharField(max_length=1000, null=True, blank=True)
    access_contraints = models.CharField(max_length=255, null=True, blank=True)
    connection_params = models.TextField(null=True, blank=True)
    username = models.CharField(max_length=50, null=True, blank=True)
    password = models.CharField(max_length=50, null=True, blank=True)
    api_key = models.CharField(max_length=255, null=True, blank=True)
    workspace_ref = models.URLField(False, null=True, blank=True)
    store_ref = models.URLField(null=True, blank=True)
    resources_ref = models.URLField(null = True, blank = True)
    profiles = models.ManyToManyField(Profile, through='ServiceProfileRole')
    owner = models.ForeignKey(User, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    first_noanswer = models.DateTimeField(null=True, blank=True)
    noanswer_retries = models.PositiveIntegerField(null=True, blank=True)
    uuid = models.CharField(max_length=36, null=True, blank=True)
    external_id = models.IntegerField(null=True, blank=True)
    parent = models.ForeignKey('services.Service', null=True, blank=True, related_name='service_set')
    layers = models.ManyToManyField(Layer, through='ServiceLayer')

    # Supported Capabilities

    def __unicode__(self):
        return self.name

    @property
    def ptype(self):
        # Return the gxp ptype that should be used to display layers
        return GXP_PTYPES[self.type]

    def get_absolute_url(self):
        return '/services/%i' % self.id

    class Meta:
        # custom permissions,
        # change and delete are standard in django
        permissions = (('view_service', 'Can view'),
                       ('change_service_permissions', "Can change permissions"), )

    # Permission Level Constants
    # LEVEL_NONE inherited
    LEVEL_READ  = 'service_readonly'
    LEVEL_WRITE = 'service_readwrite'
    LEVEL_ADMIN = 'service_admin'


    def set_default_permissions(self):
        self.set_gen_level(ANONYMOUS_USERS, self.LEVEL_READ)
        self.set_gen_level(AUTHENTICATED_USERS, self.LEVEL_READ)
        #self.set_gen_level(CUSTOM_GROUP_USERS, self.LEVEL_READ)

        # remove specific user permissions
        current_perms =  self.get_all_level_info()
        for username in current_perms['users'].keys():
            user = User.objects.get(username=username)
            self.set_user_level(user, self.LEVEL_NONE)

        # assign owner admin privs
        if self.owner:
            self.set_user_level(self.owner, self.LEVEL_ADMIN)

class ServiceProfileRole(models.Model):
    """
    ServiceProfileRole is an intermediate model to bind Profiles and Services and apply roles.
    """
    profiles = models.ForeignKey(Profile)
    service = models.ForeignKey(Service)
    role = models.ForeignKey(Role)

class ServiceLayer(models.Model):
    service = models.ForeignKey(Service)
    layer = models.ForeignKey(Layer, null=True)
    typename = models.CharField(_("Layer Name"), max_length=255)
    title = models.CharField(_("Layer Title"), max_length=512)
    description = models.TextField(_("Layer Description"), null=True)
    styles = models.TextField(_("Layer Styles"), null=True)


class WebServiceHarvestLayersJob(models.Model):
    service = models.ForeignKey(Service, blank=False, null=False, unique=True)
    status = models.CharField(choices= [(x, x) for x in STATUS_VALUES], max_length=10, blank=False, null=False, default='pending')

class WebServiceRegistrationJob(models.Model):
    base_url = models.URLField(unique=True)
    type = models.CharField(max_length=4, choices=SERVICE_TYPES)
    status = models.CharField(choices= [(x, x) for x in STATUS_VALUES], max_length=10, blank=False, null=False, default='pending')

def post_save_service(instance, sender, created, **kwargs):
    if created:
        instance.set_default_permissions()

def pre_delete_service(instance, sender, **kwargs):
    for layer in instance.layers.all():
        layer.delete()
    # if instance.method == 'H':
    #     gn = Layer.objects.gn_catalog
    #     gn.control_harvesting_task('stop', [instance.external_id])
    #     gn.control_harvesting_task('remove', [instance.external_id])
    if instance.method == 'C':
        try:
            gs = Layer.objects.gs_catalog
            cascade_store = gs.get_store(instance.name, settings.CASCADE_WORKSPACE)
            gs.delete(cascade_store, recurse=True)
        except FailedRequestError:
            logger.error("Could not delete cascading WMS Store for %s - maybe already gone" % instance.name)



signals.pre_delete.connect(pre_delete_service, sender=Service)
signals.post_save.connect(post_save_service, sender=Service)

geonode/contrib/services/forms.py
from django import forms
import taggit
from geonode.contrib.services.models import Service, ServiceLayer
from geonode.contrib.services.enumerations import SERVICE_TYPES, SERVICE_METHODS
from django.utils.translation import ugettext_lazy as _

class CreateServiceForm(forms.Form):
    # name = forms.CharField(label=_("Service Name"), max_length=512,
    #     widget=forms.TextInput(
    #         attrs={'size':'50', 'class':'inputText'}))
    url = forms.CharField(label=_("Service URL"), max_length=512,
                               widget=forms.TextInput(
                                   attrs={'size':'65', 'class':'inputText'}))
    type = forms.ChoiceField(label=_("Service Type"),choices=SERVICE_TYPES,initial='AUTO',required=True)
    # method = forms.ChoiceField(label=_("Service Type"),choices=SERVICE_METHODS,initial='I',required=True)


class ServiceForm(forms.ModelForm):
    title = forms.CharField(label =  _('Title'), max_length=255, widget=forms.TextInput(
        attrs={'size':'60', 'class':'inputText'}))
    description = forms.CharField(label = _('Description'), widget=forms.Textarea(attrs={'cols': 60}))
    abstract = forms.CharField(label=_("Abstract"), widget=forms.Textarea(attrs={'cols': 60}))
    keywords = taggit.forms.TagField(required=False)

    class Meta:
        model = Service
        fields = ('title', 'description', 'abstract', 'keywords', )


class ServiceLayerFormSet(forms.ModelForm):
        class Meta:
            model = ServiceLayer
            fields = ('typename',)

geonode/contrib/services/templates/services/layers_register.html
{% extends "services/services_base.html" %}
{% load i18n %}
{% block head %}
{{ block.super }}
<script type="text/javascript">
    $(function () {
        $("#checkall").on('click', function () {
            $('input[name=layer_list]').prop('checked', this.checked);
        });
    });
</script>
{% endblock %}

{% block title %} Services -- Available Layers {{ block.super }} {% endblock %}

{% block body %}
<div class="twocol">
    {% if service %}
    <h1>Select Layers to Import</h1>
     <form method="POST">
      {% csrf_token %}

         <table class="table table-striped table-bordered table-condensed">
             <thead>
             <tr>
                 <th><input type="checkbox" checked="true" id="checkall" />{% trans "All/None" %}</th>
                 <th>{% trans "Name" %}</th>
                 <th>{% trans "Description" %}</th>
             </tr>
             </thead>
             <tbody>
             {% for layer in service.servicelayer_set.all %}
             <tr>
                 <td><input type="checkbox" name="layer_list" id="option_{{layer.typename}}" value="{{ layer.typename }}" checked="false"  /></td>
                 <td>{{ layer.typename }}</td>
                 <td>{{ layer.description }}</td>
             </tr>
             {% endfor %}

             </tbody>
         </table>
         <div align="center"><p><input type="submit" class="submit_btn" value="{% trans "Add Layers" %}" /></p></div>
     </form>
    {% else %}
    <h3>No layers found</h3>
    {% endif %}
</div>
{% endblock %}

geonode/contrib/services/templates/services/service_detail.html
{% extends "services/services_base.html" %}
{% load i18n %}
{% load geonode_auth %}

{% block head %}
{% include "geonode/ext_header.html" %}
{% include "geonode/app_header.html" %}
{% include "geonode/geo_header.html" %}
{{ block.super }}
<script type="text/javascript">
var app;
{% autoescape off %}
Ext.onReady(function() {
{% has_obj_perm user service "maps.change_service_permissions" as can_change_permissions %}

{% if can_change_permissions %}
       new GeoNode.WorldMapPermissionsEditor({
                renderTo: "permissions_form",
                submitTo: "{% url "geonode.contrib.services.views.ajax_service_permissions" service.id %}",
                userLookup: "{% url "geonode.views.ajax_lookup" %}",
                customGroup: "{{ customGroup }}",
                permissions: {{ permissions_json }},
        levels: {
            'admin': 'layer_admin',
                    'readwrite': 'layer_readwrite',
                    'readonly': 'layer_readonly',
                    'none': '_none'
        },
        listeners: {
            updated: function(perms) {
                var submitTo = "{% url "geonode.contrib.services.views.ajax_service_permissions" service.id %}";
                Ext.Ajax.request({ url: submitTo, jsonData: perms.writePermissions() });
            }
        }
    });
    {% endif %}
});
{% endautoescape %}
</script>
{% endblock %}

{% block body %}
<div class="twocol">
  <h3>{{service.title|default:service.name}}</h3>
  <p><strong>{% trans "Name:" %}</strong> {{service.name}}</p>
  <p><strong>{% trans "URL:" %}</strong> {{service.base_url}}</p>
  <p><strong>{% trans "Abstract:" %}</strong> {{service.abstract}}</p>
  <p><strong>{% trans "Keywords:" %}</strong> {{ service.keywords.all|join:", " }}</p>
  <p><strong>{% trans "Contact:" %}</strong> <a href="{{ service.owner.get_profile.get_absolute_url }}">{{ service.owner }}</a></p>

    {% autoescape off %}
    {%  if services %}
        <h3>{% trans "Services" %}</h3>
        <p>{% trans "This CSW server contains the following services" %} </p>
        <table>
            <tr><th style="width:50%">Title</th><th>Description</th></tr>
            {% for service in services %}
                    <tr>
                        <td><a href='{%  url service_detail service.id %}'>{{service.title}}</a></td>
                        <td>{{service.abstract}}</td>
                    </tr>
            {% endfor %}
        </table>
    {% endif %}
    {% if layers %}
    <h3>{% trans "Layers" %}</h3>
    <p>{% trans "This Service contains the following layers" %} </p>
    <table>
        <tr><th style="width:50%">Title</th><th>Description</th></tr>
        {% for layer in layers %}
            {% if not layer.group == "background" %}
            <tr>
                <td><a href='{{ layer.get_absolute_url }}'>{{layer.title}}</a></td>
                <td>{{layer.abstract}}</td>
            </tr>
            {% endif %}
        {% endfor %}
        <tr>
            <td colspan="2">
                <div class="pagination">
                    <span class="step-links">
                    {% if layers.has_previous %}
                        <a href="?page={{ layers.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                            Page {{ layers.number }} of {{ layers.paginator.num_pages }}.
                    </span>

                    {% if layers.has_next %}
                        <a href="?page={{ layers.next_page_number }}">next</a>
                    {% endif %}
                    </span>
                </div>
            </td>

        </tr>
    </table>
    {%  endif %}

    {% endautoescape %}

</div>
{% endblock %}
{% block sidebar %}
<div id="sidebar" class="threecol">

    {% has_obj_perm user service "maps.change_service" as can_change %}
    {% has_obj_perm user service "maps.delete_service" as can_remove %}
    {% has_obj_perm user service "maps.change_service_permissions" as can_change_permissions %}
    {% if can_change or can_remove or can_change_permissions %}
        <h3>{% trans "Manage" %}</h3>
        <ul>
        {% if can_change %}
            <li><a href="{% url "edit_service" service.id %}">{% trans "Edit Service Metadata" %}</a></li>
        {% endif %}
        {% if can_remove %}
            <li><a href="{% url "remove_service" service.id %}">{% trans "Remove Service" %}</a></li>
        {% endif %}
        </ul>
    {% endif %}
</div>
{% endblock %}

geonode/contrib/services/templates/services/service_edit.html
{% extends "services/services_base.html" %}
{% load i18n %}

{% block head %}
{{ block.super }}


{% endblock %}

{% block title %} Edit Service - {{ block.super }} {% endblock %}

{% block body %}
    <div class="onecol">

        <h2>Edit Service</h2>
        <form method="POST" id="service_edit_form">
            {% csrf_token %}
            <ul class="form">
                {{ service_form.as_ul }}
            </ul>
            <div align="center"><p><input type="submit" class="submit_btn" value="{% trans "Save" %}" /></p></div>
        </form>
    </div>
{% endblock %}

geonode/contrib/services/templates/services/service_layers.html
{% load i18n %}
<div class="twocol">
    <p>{% trans "Service:" %} <a href="{% url service_detail service.id %}">{{ service.title }}</a></p>
    {% if layers.count > 0 %}
    <p>{% trans "The following layers will soon be added to the data catalog:" %}</p>
    <table>
        {% for layer in layers %}
        <tr><td>{{ layer.0 }}</td><td>{{ layer.1|default:"" }}</td></tr>
        {% endfor %}
    </table>
    {% else %}
    <h3>No layers</h3>
    {% endif %}
</div>

geonode/contrib/services/templates/services/service_list.html
{% extends "services/services_base.html" %}
{% load i18n %}

{% block title %} Services -- {{ block.super }} {% endblock %}

{% block body %}
<div class="twocol">
{% if services %}
<table>
    <tr>
        <th>Title</th><th>URL</th>
    </tr>

{% for service in services %}
<tr>
<td><a href='{% url "service_detail" service.id %}'>{{ service.title }}</a></td>
<td><a href='{% url "service_detail" service.id %}'>{{ service.base_url }}</a></td>
</tr>
{% endfor %}
</table>
{% else %}
<h3>No services registered</h3>
{% endif %}
</div>
{% endblock %}

{% block sidebar %}
<div id="sidebar" class="threecol">

    <h3>{% trans "Manage" %}</h3>
    <ul>
        <li><a href="{% url "register_service" %}">{% trans "Register a new Service" %}</a></li>
    </ul>

</div>
{% endblock %}

geonode/contrib/services/templates/services/service_register.html
{% extends "services/services_base.html" %}
{% load i18n %}

{% block head %}
{{ block.super }}

<script type="text/javascript">
$( document ).ready(function() {
    $("#service_register_form").submit(function(e) {
        $("#responseDiv").hide();
        $(".result").remove();
        $("#tableDiv").hide();
        $("#dataTable").html("");
        $(".error").html("");

        e.preventDefault();
        var url = $("#service_register_form").attr( "action" );
        $.ajax({
            type: "POST",
            url: url,
            dataType: "json",
            data: $("#service_register_form").serialize(), // serializes the form's elements.
            success: function(data)
            {
                for (var item in data) {
                    if (data[item].available_layers) {
                        $.each(data[item].available_layers,function(i,row){
                            $('<tr>').attr('id',i).
                                    append($('<td>').text(row[0])).
                                    append($('<td>').text(row[1])).appendTo('#dataTable');
                        });
                        $("#tableDiv").show();
                    }
                    if (data[item].service_id) {
                        $('<div>').attr("class", "result").append($('<a>').
                            attr('href', "/services/" + data[item].service_id).
                            text(data[item].service_title||data[item].service_name)).
                            appendTo("#responseDiv");
                    }
                    else {
                       $('<h4>').attr("class", "result").text(data[item].msg).appendTo("#responseDiv");
                    }
                    $("#responseDiv").show();
                }

            },
            error: function(data) {
                $(".error").html(data.responseText);
                $(".error").show();
            }
        });

        return false; // avoid to execute the actual submit of the form.
    });
});
</script>


{% endblock %}

{% block title %} Register Service - {{ block.super }} {% endblock %}

{% block body %}
<div class="twocol">

<h2>Register New Service</h2>
    <form method="POST" id="service_register_form">
    {% csrf_token %}
    <ul class="form">
        {{ create_service_form.as_ul }}
    </ul>
    <div align="center"><p><input type="submit" class="submit_btn" value="{% trans "Create" %}" /></p></div>
    </form>

    <div id="responseDiv" style="display:none;">
        <h4>{%  trans "Service has been created:" %}</h4>
    </div>

    <div class="error" style="display:none;">
    </div>

    <div id="tableDiv" style="display:none;">
        <p><a id="service_link">{%  trans "The following layers will be imported" %}</a></p>
        <table id="dataTable"></table>
    </div>
</div>
{% endblock %}

geonode/contrib/services/templates/services/service_remove.html
{% extends "services/services_base.html" %}
{% load i18n %}

{% block title %} {{ service.name }} - {{ block.super }} {% endblock %}

{% block body %}
<h3>{% trans "Are you sure you want to remove"  %} <strong>{{ service.name }}</strong>?</h3>

<div style="float:left;">
    <form action="/services/{{service.id}}/remove" method="POST" class="inline">
        {% csrf_token %}
        <input type="hidden" value="{{next}}" id="next" name="next">
        <input type="submit" class="submit_btn" value="{% trans "Yes, delete"  %}" />
    </form>
    <form action="/services/{{service.id}}" method="GET" class="inline">
        <button type="submit"  class="cancel_btn" onclick="javascript: history.go(-1);return false;">{% trans "No, cancel" %}</button>
    </form>
</div>
<div style="float:left;">

{% endblock %}

geonode/contrib/services/templates/services/services_base.html
{% extends "site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}data{% endblock %}

{% comment %}
{% block body_outer %}
    <div class="span12">
      <!--nav class="back"><a href="{% url "layer_browse" %}"><i class="icon-chevron-left"></i> See all Layers</a></nav-->
      <ul class="nav nav-tabs" id="subnav-tabs">
            <li><a href="{% url "layer_browse" %}" class="explore">{% trans "Explore Layers" %}</a></li>
            <!-- switch to us the new upload -->
            <li><a href="{% url "data_upload" %}" class="upload">{% trans "Upload Layers" %}</a></li>
      </ul>
    </div>
    {% block body %}{% endblock body %}
    {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}
{% endcomment %}