geonode/api/urls.py
from django.conf.urls import patterns, include, url

from tastypie.api import Api

from .api import  UserResource, TagResource, TopicCategoryResource, ProfileResource, GroupResource
from .resourcebase_api import LayerResource, MapResource, DocumentResource, ResourceBaseResource, \
    FeaturedResourceBaseResource

api = Api(api_name='api')

api.register(LayerResource())
api.register(MapResource())
api.register(DocumentResource())
api.register(UserResource())
api.register(ProfileResource())
api.register(ResourceBaseResource())
api.register(TagResource())
api.register(TopicCategoryResource())
api.register(GroupResource())
api.register(FeaturedResourceBaseResource())

geonode/maps/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls.defaults import patterns, url
from django.views.generic import TemplateView

js_info_dict = {
    'packages': ('geonode.maps',),
}

urlpatterns = patterns('geonode.maps.views',
    url(r'^$', TemplateView.as_view(template_name='maps/map_list.html'), name='maps_browse'),
    url(r'^new$', 'new_map', name="new_map"),
    url(r'^new/data$', 'new_map_json', name='new_map_json'),
    url(r'^(?P<mapid>\d+)$', 'map_detail', name='map_detail'),
    url(r'^(?P<mapid>\d+)/view$', 'map_view', name='map_view'),
    url(r'^(?P<mapid>\d+)/data$', 'map_json', name='map_json'),
    url(r'^(?P<mapid>\d+)/download$', 'map_download', name='map_download'),
    url(r'^(?P<mapid>\d+)/wmc$', 'map_wmc', name='map_wmc'),
    url(r'^(?P<mapid>\d+)/wms$', 'map_wms', name='map_wms'),
    url(r'^(?P<mapid>\d+)/remove$', 'map_remove', name='map_remove'),
    url(r'^(?P<mapid>\d+)/metadata$', 'map_metadata', name='map_metadata'),
    url(r'^(?P<mapid>\d+)/embed$', 'map_embed', name='map_embed'),
    url(r'^(?P<mapid>\d+)/thumbnail$', 'map_thumbnail', name='map_thumbnail'),
    url(r'^check/$', 'map_download_check', name='map_download_check'),
    url(r'^embed/$', 'map_embed', name='map_embed'),
    url(r'^(?P<layername>[^/]*)/attributes', 'maplayer_attributes', name='maplayer_attributes'),
    #url(r'^change-poc/(?P<ids>\w+)$', 'change_poc', name='maps_change_poc'),
)

geonode/proxy/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls.defaults import patterns

urlpatterns = patterns('geonode.proxy.views',
    (r'^proxy/', 'proxy'),
)

geonode/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView

import geonode.proxy.urls

from geonode.api.urls import api

# Setup Django Admin
from django.contrib import admin
admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

urlpatterns = patterns('',

    # Static pages
    url(r'^/?$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
    url(r'^developer/$', TemplateView.as_view(template_name='developer.html'), name='developer'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),

    # Layer views
    (r'^layers/', include('geonode.layers.urls')),

    # Map views
    (r'^maps/', include('geonode.maps.urls')),

    # Catalogue views
    (r'^catalogue/', include('geonode.catalogue.urls')),

    # Search views
    url(r'^search/$', TemplateView.as_view(template_name='search/search.html'), name='search'),

    # Social views
    (r'^cas/', include('cas_consumer.urls')),
    (r"^account/", include("account.urls")),
    (r'^people/', include('geonode.people.urls')),
    (r'^avatar/', include('avatar.urls')),
    (r'^comments/', include('dialogos.urls')),
    (r'^ratings/', include('agon_ratings.urls')),
    (r'^activity/', include('actstream.urls')),
    (r'^announcements/', include('announcements.urls')),
    #(r'^notifications/', include('notification.urls')),
    (r'^messages/', include('user_messages.urls')),
    (r'^social/', include('geonode.social.urls')),
    # Accounts
    url(r'^account/ajax_login$', 'geonode.views.ajax_login',
                                       name='account_ajax_login'),
    url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup',
                                       name='account_ajax_lookup'),
    url(r'^security/permissions/(?P<type>[^/]*)/(?P<resource_id>\d+)$', 'geonode.security.views.resource_permissions',
                                       name='resource_permissions'),

    # Meta
    url(r'^lang\.js$', TemplateView.as_view(template_name='lang.js', content_type='text/javascript'), name='lang'),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog',
                                  js_info_dict, name='jscat'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
                                  {'sitemaps': sitemaps}, name='sitemap'),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^admin/', include(admin.site.urls)),
    url(r'', include(api.urls)),
    )

#Documents views
if 'geonode.documents' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^documents/', include('geonode.documents.urls')),
    )

if "geonode.contrib.groups" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^groups/', include('geonode.contrib.groups.urls')),
    )

if "geonode.contrib.services" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^services/', include('geonode.contrib.services.urls')),
    )

if "geonode.contrib.dynamic" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^dynamic/', include('geonode.contrib.dynamic.urls')),
    )

if 'geonode.geoserver' in settings.INSTALLED_APPS:
    # GeoServer Helper Views
    urlpatterns += patterns('', 
        # Upload views
        (r'^upload/', include('geonode.upload.urls')),
        (r'^gs/', include('geonode.geoserver.urls')),
    )

# Set up proxy
urlpatterns += geonode.proxy.urls.urlpatterns


# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

geonode/social/models.py
import geonode.social.signals

geonode/contrib/services/forms.py
from django import forms
import taggit
from geonode.contrib.services.models import Service, ServiceLayer
from geonode.contrib.services.enumerations import SERVICE_TYPES, SERVICE_METHODS
from django.utils.translation import ugettext_lazy as _

class CreateServiceForm(forms.Form):
    # name = forms.CharField(label=_("Service Name"), max_length=512,
    #     widget=forms.TextInput(
    #         attrs={'size':'50', 'class':'inputText'}))
    url = forms.CharField(label=_("Service URL"), max_length=512,
                               widget=forms.TextInput(
                                   attrs={'size':'65', 'class':'inputText'}))
    type = forms.ChoiceField(label=_("Service Type"),choices=SERVICE_TYPES,initial='AUTO',required=True)
    # method = forms.ChoiceField(label=_("Service Type"),choices=SERVICE_METHODS,initial='I',required=True)


class ServiceForm(forms.ModelForm):
    title = forms.CharField(label =  _('Title'), max_length=255, widget=forms.TextInput(
        attrs={'size':'60', 'class':'inputText'}))
    description = forms.CharField(label = _('Description'), widget=forms.Textarea(attrs={'cols': 60}))
    abstract = forms.CharField(label=_("Abstract"), widget=forms.Textarea(attrs={'cols': 60}))
    keywords = taggit.forms.TagField(required=False)

    class Meta:
        model = Service
        fields = ('title', 'description', 'abstract', 'keywords', )


class ServiceLayerFormSet(forms.ModelForm):
        class Meta:
            model = ServiceLayer
            fields = ('typename',)

geonode/documents/forms.py
import json
import os
import taggit
import re

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.conf import settings
from django.forms import HiddenInput, TextInput

from geonode.people.models import Profile
from geonode.documents.models import Document
from geonode.maps.models import Map
from geonode.layers.models import Layer

class DocumentForm(forms.ModelForm):
    date = forms.DateTimeField(widget=forms.SplitDateTimeWidget)
    date.widget.widgets[0].attrs = {"class":"datepicker", 'data-date-format': "yyyy-mm-dd"}
    date.widget.widgets[1].attrs = {"class":"time"}
    temporal_extent_start = forms.DateField(required=False,widget=forms.DateInput(attrs={"class":"datepicker", 'data-date-format': "yyyy-mm-dd"}))
    temporal_extent_end = forms.DateField(required=False,widget=forms.DateInput(attrs={"class":"datepicker", 'data-date-format': "yyyy-mm-dd"}))
    
    resource = forms.ChoiceField(label='Link to')

    poc = forms.ModelChoiceField(empty_label = "Person outside GeoNode (fill form)",
                                 label = "Point Of Contact", required=False,
                                 queryset = Profile.objects.exclude(user=None))

    metadata_author = forms.ModelChoiceField(empty_label = "Person outside GeoNode (fill form)",
                                             label = "Metadata Author", required=False,
                                             queryset = Profile.objects.exclude(user=None))
    keywords = taggit.forms.TagField(required=False,
                                     help_text=_("A space or comma-separated list of keywords"))
    
    def __init__(self, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        rbases = list(Layer.objects.all())
        rbases += list(Map.objects.all())
        rbases.sort(key=lambda x: x.title)
        rbases_choices = []
        rbases_choices.append(['no_link', '---------'])
        for obj in rbases:
            type_id = ContentType.objects.get_for_model(obj.__class__).id
            obj_id = obj.id
            form_value = "type:%s-id:%s" % (type_id, obj_id)
            display_text = '%s (%s)' % (obj.title, obj.polymorphic_ctype.model)
            rbases_choices.append([form_value, display_text])
        self.fields['resource'].choices = rbases_choices
        if self.instance.content_type:
            self.fields['resource'].initial = 'type:%s-id:%s' % (
                self.instance.content_type.id, self.instance.object_id)
    
    def save(self, *args, **kwargs):
        contenttype_id = None
        contenttype = None
        object_id = None
        resource = self.cleaned_data['resource']
        if resource != 'no_link':
            matches = re.match("type:(\d+)-id:(\d+)", resource).groups()
            contenttype_id = matches[0]
            object_id = matches[1]
            contenttype = ContentType.objects.get(id=contenttype_id)
        self.cleaned_data['content_type'] = contenttype_id
        self.cleaned_data['object_id'] = object_id
        self.instance.object_id = object_id
        self.instance.content_type = contenttype
        return super(DocumentForm, self).save(*args, **kwargs)
        
    class Meta:
        model = Document
        exclude = ('contacts','workspace', 'store', 'name', 'uuid', 'storeType',
                   'typename', 'bbox_x0', 'bbox_x1', 'bbox_y0', 'bbox_y1', 'srid',
                   'csw_typename', 'csw_schema', 'csw_mdsource', 'csw_type',
                   'csw_wkt_geometry', 'metadata_uploaded', 'metadata_xml', 'csw_anytext', 
                   'content_type', 'object_id', 'doc_file', 'extension', 
                   'popular_count', 'share_count', 'thumbnail', 'doc_url')

class DocumentDescriptionForm(forms.Form):
    title = forms.CharField(300)
    abstract = forms.CharField(1000, widget=forms.Textarea, required=False)
    keywords = forms.CharField(500, required=False)

class DocumentReplaceForm(forms.ModelForm):
    """
    The form used to replace a document.
    """

    class Meta:
        model = Document
        fields = ['doc_file', 'doc_url']

    def clean(self):
        """
        Ensures the doc_file or the doc_url field is populated.
        """
        cleaned_data = super(DocumentReplaceForm, self).clean()
        doc_file = self.cleaned_data.get('doc_file')
        doc_url = self.cleaned_data.get('doc_url')

        if not doc_file and not doc_url:
            raise forms.ValidationError(_("Document must be a file or url."))

        if doc_file and doc_url:
            raise forms.ValidationError(_("A document cannot have both a file and a url."))

        return cleaned_data

    def clean_doc_file(self):
        """
        Ensures the doc_file is valid.
        """
        doc_file = self.cleaned_data.get('doc_file')

        if doc_file and not os.path.splitext(doc_file.name)[1].lower()[1:] in settings.ALLOWED_DOCUMENT_TYPES:
            raise forms.ValidationError(_("This file type is not allowed"))

        return doc_file


class DocumentCreateForm(forms.ModelForm):
    """
    The document upload form.
    """
    permissions = forms.CharField(widget=HiddenInput(attrs={'name': 'permissions', 'id': 'permissions'}), required=True)
    resource = forms.CharField(required=False, label=_("Link to"), widget=TextInput(attrs={'name': 'q',
                                                                                           'id': 'resource'}))

    class Meta:
        model = Document
        fields = ['title', 'doc_file', 'doc_url']
        widgets = {
            'name': HiddenInput(attrs={'cols': 80, 'rows': 20}),
        }

    def clean_permissions(self):
        """
        Ensures the JSON field is JSON.
        """
        permissions = self.cleaned_data['permissions']

        try:
            return json.loads(permissions)
        except ValueError:
            raise forms.ValidationError(_("Permissions must be valid JSON."))

    def clean(self):
        """
        Ensures the doc_file or the doc_url field is populated.
        """
        cleaned_data = super(DocumentCreateForm, self).clean()
        doc_file = self.cleaned_data.get('doc_file')
        doc_url = self.cleaned_data.get('doc_url')

        if not doc_file and not doc_url:
            raise forms.ValidationError(_("Document must be a file or url."))

        if doc_file and doc_url:
            raise forms.ValidationError(_("A document cannot have both a file and a url."))

        return cleaned_data

    def clean_doc_file(self):
        """
        Ensures the doc_file is valid.
        """
        doc_file = self.cleaned_data.get('doc_file')

        if doc_file and not os.path.splitext(doc_file.name)[1].lower()[1:] in settings.ALLOWED_DOCUMENT_TYPES:
            raise forms.ValidationError(_("This file type is not allowed"))

        return doc_file

geonode/templates/401.html
{% extends "site_base.html" %}
{% load i18n %}

{% block body %}
    <div id="description"> 
      <h3> 
        {% if error_title %}
          {{ error_title }}
        {% else %}
          {% trans "Not Permitted" %}
        {% endif %}
      </h3>
    </div>
    <p>
    {% if error_message %}
      {{ error_message }}
    {% else %}
      {% blocktrans %}
          You are not allowed to perform this operation.  
      {% endblocktrans %}
    {% endif %}
    </p>
    <p>
    {% if not request.user.is_anonymous %}
    {% blocktrans %}Please verify that you are logged in as the correct user.{%endblocktrans%}
    {% else %}
    {% blocktrans %}Please login or register and retry.{% endblocktrans %}
    {% endif %}
    </p>
{% endblock %}

geonode/templates/_actions.html
{% load i18n %}
<div class="map-actions">
  <a href="#" data-toggle="collapse" data-target="#info"><i class="icon-info-sign"></i> {% trans 'Info' %}</a>
  <a href="#"><i class="icon-heart"></i> {% trans 'Add to Favorites' %}</a>
  <a href="#"><i class="icon-share"></i> {% trans 'Share' %}</a>
  <a href="#" data-toggle="collapse" data-target="#rate-map"><i class="icon-star"></i> {% trans 'Rate this Map' %}</a>
</div>

geonode/templates/_comments.html
{% load dialogos_tags %}
{% load bootstrap_tags %}
{% load pagination_tags %}
{% load url from future %}
{% load friendly_loader %}
{% load i18n %}
{% friendly_load avatar_tags %}

{% load i18n %}
<div id="comments_section" class="comments paginate paginate-manual">
  <header>
    <h3>{% trans 'Comments' %} <span class="total">({% comment_count obj %} total)</span></h3>
  </header>

  {% if user.is_authenticated %}
  <div class="clearfix">
    <a href="#form_post_comment_div" role="button" class="btn pull-right" data-toggle="modal">{% trans 'Add Comment' %}</a>
  </div>
  {% else %}
  <div class="clearfix">
    <p class="pull-right">{% trans 'Log in to add a comment' %}</p>
  </div>
  {% endif %}
  <div class="paginate-contents">
  {% comments obj as comment_list %}
  {% autopaginate comment_list 5 %}
  {% for comment in comment_list %}      
    <article>
      <div class="avatar span1"><a href="{{ comment.author.get_profile.get_absolute_url }}">{% avatar comment.author 40 %}</a></div>
      <div class="pull-left span7">
        <p>{{ comment.comment }}</p>
        <footer>
          <div class="author clearfix span7">
            <p>{% trans 'By' %} <a href="{{ comment.author.get_profile.get_absolute_url }}" rel="author">{{ comment.author }}</a> on <time>{{ comment.submit_date|date:"M j, Y" }}</time></p>
          </div>
        </footer>
      </div>
    </article>
  {% endfor %}
  </div>
  {% paginate %}
</div>

<!-- Modal -->
{% if user.is_authenticated %}
<div id="form_post_comment_div" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>{% trans 'Add a Comment' %}</h3>
    </div>
    <div class="modal-body">
        {% comment_form obj as form %}
        <form action="{% comment_target obj %}" method="POST" id="form_post_comment">
        {% csrf_token %}
        {{ form }}
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">{% trans "Cancel" %}</button>
        <button id="comment_submit_btn" class="btn btn-primary">{% trans 'Submit Comments' %}</button>
    </div>
        </form>
</div>
{% endif %}

geonode/templates/_permissions.html
{% load i18n %}
<div class="modal-body" id="permissions-body" >
  <div class="control-group" id="permission-view-download" >
    <label class="control-label"><strong>{% trans "Who can view and download this data?" %}</strong></label>
    <div class="controls">
      <label class="radio inline">
        <input type="radio" name="viewmode" id="perms_view_anyone" value="ANYONE" checked="checked">
        {% trans "Anyone" %}
      </label>
      <label class="radio inline">
        <input type="radio" name="viewmode" id="perms_view_registered" value="REGISTERED">
        {% trans "Any registered user" %}
      </label>
      <label class="radio inline">
        <input type="radio" name="viewmode" id="perms_view_editors" value="EDITORS">
        {% if GROUPS_APP %}
            {% trans "Only users and groups who can edit" %}
        {% else %}
            {% trans "Only users who can edit" %}
        {% endif %}
      </label>
    </div>
  </div>
  <div class="control-group" id="permission-edit" >
    <label class="control-label"><strong>{% trans "Who can edit this data?" %}</strong></label>
    <div class="controls">
      <label class="radio">
        <input type="radio" name="editmode" id="perms_edit_registered" value="REGISTERED" checked="checked">
        {% trans "Any registered user" %}
      </label>
      <label class="radio">
        <input type="radio" name="editmode" id="perms_edit_list" value="LIST">
        {% if GROUPS_APP %}
            {% trans "Only the following users or groups:" %}
        {% else %}
            {% trans "Only the following users:" %}
        {% endif %}
      </label>
      <input type="text" name="editusers" class="user-select" id="perms_edit_editusers">
      {% if GROUPS_APP %}
          <input type="text" name="editgroups" class="group-select" id="perms_edit_editgroups">
      {% endif %}
      </input>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label"><strong>{% trans "Who can manage and edit this data?" %}</strong></label>
    <div class="controls">
      <input type="text" name="manageusers" class="user-select" id="perms_edit_manageusers">
      {% if GROUPS_APP %}
          <input type="text" name="managegroups" class="group-select" id="perms_edit_managegroups">
      {% endif %}
      </input>
    </div>
  </div>
</div>

geonode/templates/_permissions_form.html
{% load i18n %}

<div class="modal fade" id="modal_perms" style="display:none">
  <form id="permission_form" accept-charset="UTF-8" method="post" class="modal-form" action="{% if layer %}{% url "resource_permissions" 'layer' layer.id %}{% elif map %}{% url "resource_permissions" 'map' map.id %}{% elif document %}{% url "resource_permissions" 'document' document.id %}{% else %}/api/batch_permissions{% endif %}">
    <div class="modal-header">
      <a class="close" data-dismiss="modal">×</a>
      <h3>{% trans "Permissions" %}</h3>
    </div>
    {% include "_permissions.html" %}
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">{% trans "Cancel" %}</a>
      <a href="#" class="btn btn-primary" data-dismiss="modal" id="perms_submit">{% trans "Apply Changes" %}</a>
    </div>
  </form>
</div>

geonode/templates/_search_js.html
<script>
    $(document).ready(function() {

        $("form.geonode-search").submit(function(e) {
            e.preventDefault();
            var url = $(this).data("search-api");
            var table = $(this).data("results-table");
            var query = $(this).find("input[name=q]").val();

            // Empty results
            $(table).find("tbody").empty();

            // Get results from API
            $.getJSON(url, { q: query }, function(json) {
                if (json["total"] < 1) {
                    $(table).find("tbody:last").append($("#searchNoResultsTemplate").html());
                } else {
                    // Compile template used to render search rows
                    var _results = Hogan.compile($("#searchResultsTemplate").html(), {delimiters: "<% %>"});
                    var results = _results.render(json);
                    $(table).find("tbody:last").append(results).find("abbr.timeago").timeago();
                }
             });
        });

        // Grab url params for initial search
        var urlParams = {};
        (function () {
            var e,
                a = /\+/g,  // Regex for replacing addition symbol with a space
                r = /([^&=]+)=?([^&]*)/g,
                d = function (s) { return decodeURIComponent(s.replace(a, " ")); },
                q = window.location.search.substring(1);

            while (e = r.exec(q))
               urlParams[d(e[1])] = d(e[2]);
        })();
        if (urlParams["q"]) {
          $("input[name=q]").val(urlParams["q"]);
        };
        $("form.geonode-search").submit();
    });
</script>

geonode/templates/about.html
{% extends "site_base.html" %}

{% load i18n %}
{% block title %} {% trans "About GeoNode" %} — {{ block.super }} {% endblock %}

{% block body %}
  <header class="jumbotron subhead" id="overview">
    <h1>{% trans "About GeoNode" %}</h1>
    <p class="lead">{% trans "About GeoNode." %}</p>
  </header>

  <p>Stub</p>

{% endblock %}

geonode/templates/metadata_form_js.html
{% load staticfiles %}
{% if DEBUG_STATIC %}
<script src="{% static "lib/js/bootstrap-datepicker.js" %}" type="text/javascript"></script>
{% endif %}
<script type="text/javascript">
{% autoescape off %}
    $(function() {
      $(".datepicker").datepicker();
    });
    
    $('.modal-forms').css('max-height', '500px').css('overflow-y', 'scroll');    
    $('.modal-cloose-btn').css('margin','20px');

    $('.modal-cloose-btn').click(function(){
      $('.modal-forms').modal('hide');
    });

    $('#id_resource-poc').change(function(){
      if($(this).val() === ''){
        $('#poc_form').modal();
      }
    });

    $('#id_resource-metadata_author').change(function(){
      if($(this).val() === ''){
        $('#metadata_form').modal();
      }
    });
{% endautoescape %}
</script> 

geonode/templates/site_base.html
{% extends "base.html" %}

geonode/templates/social_links.html
{% block extra_head %}
<link href="{{ STATIC_URL }}geonode/css/social_twitter.css" rel="stylesheet" />
{% endblock %}

{% block social_links %}
	<article class="tab-pane" id="share">
        <!-- TODO: Move this to a reusable template snippet -->
        <header>
            <h3>Share This Map</h3>
        </header>
        <div>
              <ul class="social">
                  <li><a href="http://www.facebook.com/sharer.php?u=http://{{ request.get_host }}{{ request.get_full_path }}" class="fb">facebook</a></li>
                  <li><a href="https://twitter.com/share?url=http://{{ request.get_host }}{{ request.get_full_path }}" class="tw">twitter</a></li>
                  <li><a href="https://plusone.google.com/_/1/confirm?hl=en&url=http://{{ request.get_host }}{{ request.get_full_path }}" class="gp">google+</a></li>
              </ul>
         </div>
        <!-- TODO: Add more sharing options -->
    </article>
{% endblock %}