geonode/documents/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.contrib.auth.decorators import login_required
from django.conf.urls.defaults import patterns, url
from django.views.generic import TemplateView

from .views import DocumentUploadView, DocumentUpdateView

js_info_dict = {
    'packages': ('geonode.documents',),
}

urlpatterns = patterns('geonode.documents.views',
    url(r'^$', TemplateView.as_view(template_name='documents/document_list.html'), name='documents_browse'),
    url(r'^(?P<docid>\d+)/?$', 'document_detail', name='document_detail'),
    url(r'^(?P<docid>\d+)/download/?$', 'document_download', name='document_download'),
    url(r'^(?P<docid>\d+)/replace$', login_required(DocumentUpdateView.as_view()), name="document_replace"),
    url(r'^(?P<docid>\d+)/remove$', 'document_remove', name="document_remove"),
    url(r'^upload/?$', login_required(DocumentUploadView.as_view()), name='document_upload'),
    url(r'^search/?$', 'document_search_page', name='document_search_page'),
    url(r'^(?P<docid>\d+)/metadata$', 'document_metadata', name='document_metadata'),
)

geonode/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView

import geonode.proxy.urls

from geonode.api.urls import api

# Setup Django Admin
from django.contrib import admin
admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

urlpatterns = patterns('',

    # Static pages
    url(r'^/?$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
    url(r'^developer/$', TemplateView.as_view(template_name='developer.html'), name='developer'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),

    # Layer views
    (r'^layers/', include('geonode.layers.urls')),

    # Map views
    (r'^maps/', include('geonode.maps.urls')),

    # Catalogue views
    (r'^catalogue/', include('geonode.catalogue.urls')),

    # Search views
    url(r'^search/$', TemplateView.as_view(template_name='search/search.html'), name='search'),

    # Social views
    (r'^cas/', include('cas_consumer.urls')),
    (r"^account/", include("account.urls")),
    (r'^people/', include('geonode.people.urls')),
    (r'^avatar/', include('avatar.urls')),
    (r'^comments/', include('dialogos.urls')),
    (r'^ratings/', include('agon_ratings.urls')),
    (r'^activity/', include('actstream.urls')),
    (r'^announcements/', include('announcements.urls')),
    #(r'^notifications/', include('notification.urls')),
    (r'^messages/', include('user_messages.urls')),
    (r'^social/', include('geonode.social.urls')),
    # Accounts
    url(r'^account/ajax_login$', 'geonode.views.ajax_login',
                                       name='account_ajax_login'),
    url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup',
                                       name='account_ajax_lookup'),
    url(r'^security/permissions/(?P<type>[^/]*)/(?P<resource_id>\d+)$', 'geonode.security.views.resource_permissions',
                                       name='resource_permissions'),

    # Meta
    url(r'^lang\.js$', TemplateView.as_view(template_name='lang.js', content_type='text/javascript'), name='lang'),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog',
                                  js_info_dict, name='jscat'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
                                  {'sitemaps': sitemaps}, name='sitemap'),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^admin/', include(admin.site.urls)),
    url(r'', include(api.urls)),
    )

#Documents views
if 'geonode.documents' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^documents/', include('geonode.documents.urls')),
    )

if "geonode.contrib.groups" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^groups/', include('geonode.contrib.groups.urls')),
    )

if "geonode.contrib.services" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^services/', include('geonode.contrib.services.urls')),
    )

if "geonode.contrib.dynamic" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^dynamic/', include('geonode.contrib.dynamic.urls')),
    )

if 'geonode.geoserver' in settings.INSTALLED_APPS:
    # GeoServer Helper Views
    urlpatterns += patterns('', 
        # Upload views
        (r'^upload/', include('geonode.upload.urls')),
        (r'^gs/', include('geonode.geoserver.urls')),
    )

# Set up proxy
urlpatterns += geonode.proxy.urls.urlpatterns


# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

geonode/documents/models.py
import logging
import os
import sys
import uuid

from django.db import models
from django.db.models import signals
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.files.base import ContentFile
from django.contrib.contenttypes import generic
from django.contrib.staticfiles import finders
from django.utils.translation import ugettext_lazy as _

from geonode.security.enumerations import AUTHENTICATED_USERS, ANONYMOUS_USERS
from geonode.layers.models import Layer
from geonode.base.models import ResourceBase, Thumbnail, Link
from geonode.maps.signals import map_changed_signal
from geonode.maps.models import Map

IMGTYPES = ['jpg', 'jpeg', 'tif', 'tiff', 'png', 'gif']

logger = logging.getLogger(__name__)

class Document(ResourceBase):
    """
    A document is any kind of information that can be attached to a map such as pdf, images, videos, xls...
    """

    # Relation to the resource model
    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    resource = generic.GenericForeignKey('content_type', 'object_id')

    doc_file = models.FileField(upload_to='documents',
                                null=True,
                                blank=True,
                                verbose_name=_('File'))

    extension = models.CharField(max_length=128, blank=True, null=True)

    doc_url = models.URLField(blank=True,
                              null=True,
                              help_text=_('The URL of the document if it is external.'),
                              verbose_name=_('URL'))

    def __unicode__(self):  
        return self.title
        
    def get_absolute_url(self):
        return reverse('document_detail', args=(self.id,))
        
    class Meta:
        # custom permissions,
        # change and delete are standard in django
        permissions = (
            ('view_document', 'Can view'), 
            ('change_document_permissions', "Can change permissions"),
        )

    LEVEL_READ  = 'document_readonly'
    LEVEL_WRITE = 'document_readwrite'
    LEVEL_ADMIN = 'document_admin'


    def _render_thumbnail(self):
        from cStringIO import StringIO

        size = 200, 150

        try:
            from PIL import Image, ImageOps
        except: 
            logger.error('%s: Pillow not installed, cannot generate thumbnails.' % e)
            return None

        try:
            # if wand is installed, than use it for pdf thumbnailing
            from wand import image
        except:
            wand_available = False
        else:
            wand_available = True

        if wand_available and self.extension and self.extension.lower() == 'pdf' and self.doc_file:
            logger.debug('Generating a thumbnail for document: {0}'.format(self.title))
            with image.Image(filename=self.doc_file.path) as img:
                img.sample(*size)
                return img.make_blob('png')
        elif self.extension and self.extension.lower() in IMGTYPES and self.doc_file:
            
            img = Image.open(self.doc_file.path)
            img = ImageOps.fit(img, size, Image.ANTIALIAS)
        else:
            filename = finders.find('documents/{0}-placeholder.png'.format(self.extension), False) or \
                       finders.find('documents/generic-placeholder.png', False)

            if not filename:
                return None

            img = Image.open(filename)

        imgfile = StringIO()
        img.save(imgfile, format='PNG')
        return imgfile.getvalue()

    @property
    def class_name(self):
        return self.__class__.__name__

def get_related_documents(resource):
    if isinstance(resource, Layer) or isinstance(resource, Map):
        ct = ContentType.objects.get_for_model(resource)
        return Document.objects.filter(content_type=ct,object_id=resource.pk)
    else: return None

def pre_save_document(instance, sender, **kwargs):
    base_name, extension = None, None

    if instance.doc_file:
        base_name, extension = os.path.splitext(instance.doc_file.name)
        instance.extension = extension[1:]
    elif instance.doc_url:
        if len(instance.doc_url) > 4 and instance.doc_url[-4] == '.':
            instance.extension = instance.doc_url[-3:]

    if not instance.uuid:
        instance.uuid = str(uuid.uuid1())
    instance.csw_type = 'document'
    
    if instance.abstract == '' or instance.abstract is None:
        instance.abstract = 'No abstract provided'

    if instance.title == '' or instance.title is None:
        instance.title = instance.name

    if instance.resource:
        instance.csw_wkt_geometry = instance.resource.geographic_bounding_box.split(';')[-1]
        instance.bbox_x0 = instance.resource.bbox_x0
        instance.bbox_x1 = instance.resource.bbox_x1
        instance.bbox_y0 = instance.resource.bbox_y0
        instance.bbox_y1 = instance.resource.bbox_y1
    else:
        instance.bbox_x0 = -180
        instance.bbox_x1 = 180
        instance.bbox_y0 = -90
        instance.bbox_y1 = 90

def create_thumbnail(sender, instance, created, **kwargs):
    if not created:
        return

    if instance.has_thumbnail():
        instance.thumbnail.thumb_file.delete()
    else:
        instance.thumbnail = Thumbnail()

    image = instance._render_thumbnail()
     
    instance.thumbnail.thumb_file.save('doc-%s-thumb.png' % instance.id, ContentFile(image))
    instance.thumbnail.thumb_spec = 'Rendered'
    instance.thumbnail.save()
    Link.objects.get_or_create(
        resource=instance.resourcebase_ptr,
        url=instance.thumbnail.thumb_file.url,
        defaults=dict(
            name=('Thumbnail'),
            extension='png',
            mime='image/png',
            link_type='image',))


def update_documents_extent(sender, **kwargs):
    model = 'map' if isinstance(sender, Map) else 'layer'
    ctype = ContentType.objects.get(model= model)
    for document in Document.objects.filter(content_type=ctype, object_id=sender.id):
        document.save()

def set_missing_info(sender, instance, created, **kwargs):
    """
    Executes mandatory post-save logic on the Document.
    """

    instance.set_missing_info()

signals.pre_save.connect(pre_save_document, sender=Document)
signals.post_save.connect(create_thumbnail, sender=Document)
signals.post_save.connect(set_missing_info, sender=Document)
map_changed_signal.connect(update_documents_extent)

geonode/documents/templates/documents/_document_filters.html
{% load i18n %}
{% load url from future %}

<ul class="nav nav-pills filter">
  <li><a href="{% url "documents_browse" %}"{% if document_filter  == "date" %} class="selected"{% endif %}>{% trans "Most recent" %}</a></li>
  <li><a href="{% url "document_browse_popular" %}"{% if document_filter == "popular_count" %} class="selected"{% endif %}>{% trans "Most popular" %}</a></li>
  <li><a href="{% url "document_browse_shared" %}"{% if document_filter == "share_count" %} class="selected"{% endif %}>{% trans "Most shared" %}</a></li>
  {% comment %}
  <li>
    <form action="." class="form-inline">
      <label for="">{% trans "sort by:" %}</label>
      <select name="sort" id="layer_sort" class="span1">
        <option value="">{% trans "Newest" %}</option>
        <option value="">{% trans "Popularity" %}</option>
      </select>
    </form>
  </li>
{% endcomment %}
</ul>

geonode/documents/templates/documents/_document_list_item.html
{% load url from future %}
{% load i18n %}
{% load agon_ratings_tags %}
{% load documents_tags %}
{% load base_tags %}
{% load geonode_auth %}

{% overall_rating document "document" as document_rating %}
{% num_ratings document as num_votes %}

{% has_obj_perm user document "documents.view_document" as can_view_document %}

{% if can_view_document %}
<article>
  <div class="content">
    <!-- <div class="abstract-placeholder">{{ document.abstract }}</div> -->
    <div class="item-header">
        <a href="{% url "document_detail" document.id %}"><img class="thumb" src="{{ document.get_thumbnail_url }}" /></a>
      <h3><i class="icon-file-text-alt"></i> <a href="{% url "document_detail" document.id %}">{{ document.title }}</a></h3>
    </div>
    <div class="details">
      <div class="meta">
        <p>Doc {% trans 'from' %} <a href="{% url "profile_detail" document.owner.username %}">{{ document.owner }}</a>, {{ document.date|timesince }} {% trans 'ago' %}</p>
        <p class="abstract">{{ document.abstract }}</p>
        <ul class="nav stats">
          <li><a href="{% url "document_detail" document.id %}"><strong>{{ document.popular_count }}</strong> {% trans "view" %}{{ document.popular_count|pluralize }}</a></li>
          <li><a href="{% url "document_detail" document.id %}#rate"><strong><span class="overall_rating"></span></strong><span class="avg_rating" data-rating="{{ document_rating }}">{% trans "Average rating" %} ({{num_votes}} {% trans "votes" %})</span></a></li>
        </ul>
      </div>
      <div class="tools">
        <p><a href="{% if document.doc_file %}{% url "document_download" document.id %}{% endif %}" class="btn btn-mini">{% trans "Download" %}</a></p>
      </div>
    </div>
  </div>
</article>
{% else %}
<article>
    <div class="content">
        <div class="item-header">
            <img class="thumb" src="{{  STATIC_URL }}/geonode/img/missing_thumb.png" />
            <h3><i class="icon-file-text-alt"></i>{{ document.title }}</h3>
        </div>
        <div class="details">
            <div class="meta">
                <p>Doc {% trans 'from' %} <a href="{% url "profile_detail" document.owner.username %}">{{ document.owner }}</a>, {{ document.date|timesince }} {% trans 'ago' %}</p>
                <p class="abstract">{%  trans "You do not have permission to view this document" %}</p>
                <ul class="nav stats">
                    <li><a><strong>{{ document.popular_count }}</strong> {% trans "view" %}{{ document.popular_count|pluralize }}</a></li>
                    <li><a><strong><span class="overall_rating"></span></strong><span class="avg_rating" data-rating="{{ document_rating }}">{% trans "Average rating" %} ({{num_votes}} {% trans "votes" %})</span></a></li>
                </ul>
            </div>
            <div class="tools">
            </div>
        </div>
    </div>
</article>
{%  endif %}

geonode/documents/templates/documents/document_base.html
{% extends "site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}documents{% endblock %}

{% block body_outer %}
    <div class="col-md-12">
      <ul class="nav nav-tabs" id="subnav-tabs">
            <li><a href="{% url "documents_browse" %}" class="explore">{% trans "Explore Documents" %}</a></li>
            <li><a href="{% url "document_upload" %}" class="upload">{% trans "Upload Documents" %}</a></li>
      </ul>
    </div>
    {% block body %}{% endblock body %}
    {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

geonode/documents/templates/documents/document_detail.html
{% extends "documents/document_base.html" %}
{% load geonode_auth %}
{% load i18n %}
{% load dialogos_tags %}
{% load agon_ratings_tags %}
{% load bootstrap_tags %}
{% load url from future %}
{% load base_tags %}

{% block title %}{{ document.title }} — {{ block.super }}{% endblock %}

{% block head %}

{{ block.super }}
{% endblock %}


{% block body_class %}documents{% endblock %}

{% block body_outer %}
  <div class="col-md-6">
    <h2 class="page-title">{{ document.title }}</h2>
  </div>
  <div class="col-md-6 action-group">
	  <div class="btn-group pull-right">
      <div class="btn-group">
        <a class="btn btn-large btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
          {% trans "Download Metadata" %}
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          {% for link in document.link_set.metadata %}
            <li><a href="{{ link.url }}">{{ link.name }} <i class="icon-chevron-right"></i></a></li>
          {% endfor %}
        </ul>
      </div>
    {% has_obj_perm user document "documents.change_document" as can_edit_document %}
    {% if can_edit_document %}
    <div class="btn-group">
      <a class="btn btn-large btn-info dropdown-toggle" data-toggle="dropdown" href="#">
        {% trans "Edit Document" %}
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><a href="{% url "document_metadata" document.id %}">{% trans "Edit Metadata" %} <i class="icon-chevron-right"></i></a></li>
        <li><a href="#modal_perms" data-toggle="modal">{% trans "Edit Permissions" %} <i class="icon-chevron-right"></i></a></li>
        <li><a href="{% url "document_replace" document.id %}">{% trans "Replace this Document" %} <i class="icon-chevron-right"></i></a></li>
        <li><a href="{% url "document_remove" document.id %}">{% trans "Remove this Document" %} <i class="icon-chevron-right"></i></a></li>
      </ul>
    </div>
    {% endif %}
    </div>
  </div>
  <div class="col-md-8">
   
      {% if document.extension|lower in imgtypes and document.doc_file %}
      <div id="embedded_map">
        <img src="{% url "document_download" document.id %}" width='100%' />
      </div>
      {% elif document.doc_file %}
        <a href="{% url "document_download" document.id %}" target="_blank">Download the {{ document }} document</a>
      {% elif  document.doc_url %}
        <a href="{{ document.doc_url }}" target="_blank">Download the {{ document }} document.</a> <i>({% trans 'External Resource' %})</i>
      {%  endif %}
       
      <div class="map-actions">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#info" data-toggle="tab"><i class="icon-info-sign"></i>{% trans "Info" %}</a></li>
          <li><a href="#comments" data-toggle="tab"><i class="icon-comment"></i> {% trans "Comments" %}</a></li>
          <li><a href="#rate" data-toggle="tab"><i class="icon-star"></i>{% trans "Ratings" %}</a></li>
          <li><a href="#share" data-toggle="tab"><i class="icon-share"></i>{% trans "Share" %}</a></li>
          <!-- li><a href="#flag" data-toggle="tab"><i class="icon-flag"></i>{% trans "Flag" %}</a></li -->
        </ul>
      </div>
      <div class="tab-content">
        {% include "base/resourcebase_info_panel.html" with resourcebase=document %}

        {% block social_links %}
        {% include "social_links.html" %}
        {% endblock %}

        <!--article id="flag" class="tab-pane">
          <p>Flag this Layer</p>
        </article-->
        
        <article id="comments" class="tab-pane">
          {% with document as obj %}
            {% include "_comments.html" %}
          {% endwith %}
        </article>
        
        <article id="rate" class="tab-pane">
          <!-- TODO: Move this to a reusable template snippet -->
          {% if request.user.is_authenticated %}
          <h3>{% trans "Rate this document" %}</h3>
          {% user_rating request.user document "document" as user_document_rating %}
          <div id="user_rating" class="category-layer"></div>
          {% endif %}
          <h3>{% trans 'Average Rating' %}</h3>
          {% overall_rating document "document" as document_rating %}
          {% num_ratings document as num_votes %}
          <div class="overall_rating" style="float:left" data-rating="{{ document_rating }}"></div> ({{num_votes}})
          <!-- TODO: Add display of who gave what rating based -->
        </article>
      </div>
  </div>
  <aside class="col-md-4">
    <div class="well">
        <h2>{% trans "Resource using this document" %}</h2>
        {% if layer.maps %}
        <p>{% trans "List of resources using this document:" %}</p>
        {% endif %}
        <ul class="unstyled space">
          {% if related.title %}
          <p>{% trans "This document is related to a " %} {{ document.content_type.name }}</p>
          <a href='{{ related.get_absolute_url }}'>{{ related.title }}</a>
          {% else %}
          <p>{% trans "This document is not related to any maps or layers" %}</p>
          {% endif %}
        </ul>
    </div>
    {% has_obj_perm user document "documents.change_document_permissions" as can_change_permissions %}
    {% if can_change_permissions %}
    <div class="well">
        <h2>{% trans "Permissions" %}</h2>
        <p>{% trans "Click the button below to change the permissions of this document." %}</p>
        <p><a href="#modal_perms" data-toggle="modal" class="btn btn-large">{% trans "Change Document Permissions" %}</a></p>
    </div>
    {% endif %}
    <div class="well">
      <h2>{% trans "About" %}</h2>
      <p>{% trans "Document Owner" %}</p>
      {% with document.owner.profile as profile %}
        {% include "people/_profile_about_item.html" %}
      {% endwith %}
      <p>{% trans "Point of Contact" %}</p>
      {% with document.poc as profile %}
        {% include "people/_profile_about_item.html" %}
      {% endwith %}
      <p>{% trans "Metadata Author" %}</p>
      {% with document.metadata_author as profile %}
        {% include "people/_profile_about_item.html" %}
      {% endwith %}
    </div>
  </aside>
  {% include "_permissions_form.html" %}
{% endblock %}
{% block extra_script %}
{% if SOCIAL_BUTTONS %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
{% endif %}
    {% if request.user.is_authenticated %}
        {% user_rating_js request.user document "document" %}
    {% else %}
        {% overall_rating document "document" as the_doc_rating %}
    {% endif %}
    <script type="text/javascript">
    $(function() {
        $('div.overall_rating').raty({
            half: true,
            readOnly: true,
            start: $('div.overall_rating').data('rating'),
            path: "{{ STATIC_URL }}lib/img/"
            {% if not request.user.is_authenticated %},
            score: {{ the_doc_rating }}
            {% endif %}
        });
        var activeTab = $('[href=' + location.hash + ']');
        activeTab && activeTab.tab('show');
    });
        {% if SOCIAL_BUTTONS %}
        (function() {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/plusone.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
        {% endif %}
    </script>
    {% include "_permissions_form_js.html" %}
{% endblock extra_script %}

geonode/documents/templates/documents/document_list.html
{% extends "documents/document_base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load url from future %}

{% block title %} {% trans "Explore Documents" %} - {{ block.super }} {% endblock %}

{% block body_class %}documents documents-list explore{% endblock %}

{% block body %}
    <div class="col-md-12">
      <h2 class="page-title">{% trans "Explore Documents" %}</h2>
    </div>
    {% include "search/_search_content.html" %}
{% endblock %}

{% block extra_script %}
  <script type="text/javascript">
    SEARCH_URL = '{% url 'api_dispatch_list' api_name='api' resource_name='documents' %}';
    FILTER_TYPE = 'document';
  </script>
  {% with include_spatial='true' %}
  {% include 'search/search_scripts.html' %}
  {% endwith %}
{% endblock extra_script %}

geonode/documents/templates/documents/document_upload.html
{% extends "documents/document_base.html" %}
{% load i18n %}

{% block title %} {% trans "Upload Document" %} - {{ block.super }} {% endblock %}

{% block body_class %}documents upload{% endblock body_class %}

{% block head %}
    {% include "geonode/ext_header.html" %}
    {% include "geonode/app_header.html" %}
    {{ block.super }}
{% endblock %}

{% block body %}
    <div class="block">
        <div class="col-md-8">
          <h2 class="page-title">{% trans "Upload Documents" %}</h2>
            <div>
                <form id="upload_form"  method="post" enctype="multipart/form-data" action="{% url "document_upload" %}">
                    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
                    {{ form.as_table }}
                    <div><br/><input class="btn" type="submit" value="Upload" /></div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block sidebar %}

<h3>{% trans "Permissions"  %}</h3>
<div>
  <form id="permission_form">
        {% include "_permissions.html" %}
  </form>
</div>

{% endblock %}

{% block extra_script %}
{% with "none" as document %}
{% include "_permissions_form_js.html" %}
{% endwith %}

<script type="text/javascript">
    $('#id_doc_file').on('change', function(){
        if($('#id_title').val() == ''){
            $('#id_title').val($('#id_doc_file').val());
        }
    });
    $("#resource").select2({
        minimumInputLength: 1,
        placeholder: 'Select layer, map or empty',
        width: 'element',
        ajax: {
          url: '',
          data: function(term,page){
            return {
              type: 'layer,map',
              q: term.replace(/[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi, '')
            }
          },
          results: function(data) {
            return {
              results: $.map(data.results,function(object){
                return {id: object.id, text: object.title, type: object._type};
              })
            }
          }          
        }
      });
    $('#resource').on('change',function(e){$('#resource_type').val($('#resource').select2('data').type)});
    $('#upload_form').submit(function(){
      $('#permissions').val(JSON.stringify(permissionsString($('#permission_form'),'documents')));
    });
</script>
{% endblock extra_script %}